### ISSUE TITLE
NuGet Package is out of date

### ISSUE THREAD

**Issue by adbrowne** [fsprojects/FSharpx.Extras#310]
I've just noticed that the nuget package here is more than a year old: http://www.nuget.org/packages/FSharpx.Core

What is required to get this updated?  

    .\build.cmd NuGet

 seems to generate the package. Is there anything I can do to help? 

I have a project that depends on FSharpx and FSharpx.Collections but these conflict at the moment.

**Comment by adbrowne** [comment]
Is there anything I can do to help with this. I have some time to put in next week but don't know what needs to be done?

**Comment by forki** [comment]
The whole infrastructure needs to be ported to the projectscaffold way.
That's a lot of work

**Comment by adbrowne** [comment]
@forki understand. Is it a matter of starting with a blank project scaffold setup and pulling it in piece by piece?

**Comment by dsyme** [comment]
The nuget package has been renamed to FSharpx.Extras and updated.

See https://github.com/fsprojects/FSharpx.Extras/pull/321#issue-65568847
