### ISSUE TITLE
Convenience method for predicate-based Option

### ISSUE THREAD

**Issue by alexfoxgill** [fsprojects/FSharpx.Extras#313]
One of the most common use cases for creating a new `Option` instance is checking a predicate and returning `Some` if true or `None` if not. I always end up defining my own method:

```
let someIf p x = if p x then Some x else None
```

which can then be piped:

```
path
|> Option.someIf File.Exists
```

It's a trivial thing to add but I thought I would raise it as an issue to see if people have objections (some may view it as clutter but I was quite surprised not to find it in the F# Core)

**Comment by gdziadkiewicz** [comment]
I also do a lot of parsing in this style and am willing to add this feature.

@alexfoxgill are you still interested in this and possibly willing to implement and submit PR?

**Comment by gdziadkiewicz** [comment]
I have added a PR with it.
