### ISSUE TITLE
Text.StructuredFormat dependences

### ISSUE THREAD

**Issue by VereshchaginaE** [fsprojects/FSharpx.Extras#324]
I publish binary packages on NuGet, which have dependences on FSharpx.Text.StructuredFormat and FSharpx.Core libraries. But when I'm trying to install them into project, NuGet raises error on cyclic dependencies like YC.Core 0.0.8.11 => FSharpx.Core 1.8.41 => YC.Tools 0.0.6.128-dev-ci => Mono.Addins 1.1 => RNGLR 0.0.3.0 => FSharpx.Text.StructuredFormat 1.10.0 => FSharpx.Extras 1.10.0 => FSharpx.Extras 1.10.0 (RNGLR is one of publishing packages).
Dependencies in .nuspec files written as
<dependency id="FSharpX.Core" version="[1.8.41]" />
<dependency id=" FSharpx.Text.StructuredFormat" version="" />
Please, publish fixed packages.

**Comment by VereshchaginaE** [comment]
Dependencies in .nuspec files written as
dependency id="FSharpX.Core" version="[1.8.41]"
dependency id="FSharpx.Text.StructuredFormat" version=""

**Comment by dsyme** [comment]
Do you think you could you send a PR with updates to the nugget package specifications? Then we can republish

**Comment by VereshchaginaE** [comment]
I am not sure I understand what you asked me to do. Could you reformulate your question, please?

**Comment by fsgit** [comment]
FSharpx.Text.StructuredFormat 1.10.2 is published which fixes this, please verify
