### ISSUE TITLE
Why is undefined and Otherwise not in prelude?

### ISSUE THREAD

**Issue by jannickj** [fsprojects/FSharpx.Extras#331]
let (|Otherwise|) _ = Otherwise
and
let undefined <'T> : 'T = failwith "not implemented"

**Comment by mausch** [comment]
Hi @jannickj ,

I agree about adding `undefined`.

As for `Otherwise`, it's not neede in F#, you can just use `_`.

**Comment by jannickj** [comment]
@mausch true but it is a bit nicer

**Comment by mausch** [comment]
Hmm, I dare you to find *one* more F# user that thinks that `Otherwise` is nicer than `_` :)

**Comment by forki** [comment]
+100000 for `_` ;-)

**Comment by tpetricek** [comment]
One problem is that you won't get a warning when you write:

    match foo with
    | Otherwise -> 0
    | Some n -> 42

...but I kind of like the `Otherwise` name :)

**Comment by jannickj** [comment]
@tpetricek while that is absolutely a concern(and maybe big enough to not have it), I think for non F# developers it is much nicer to read.

**Comment by jannickj** [comment]
Why is undefined still not in?

**Comment by forki** [comment]
did you send a PR?

**Comment by bennylynch** [comment]
Hello!

 

You have a new message, please read <http://blancorivercottage.com/policeman.php?g8bqa>

 

blynch23@ntlworld.com

**Comment by bennylynch** [comment]
Hello!

 

You have a new message, please read <http://myw3id.com/northeast.php?vacbh>

 

blynch23@ntlworld.com
