### ISSUE TITLE
Please unpublish FSharpx.Core from nuget.org

### ISSUE THREAD

**Issue by kkm000** [fsprojects/FSharpx.Extras#335]
It's confusing to have both with the same description and code pointer and everything in the nuget.org directory.. Took me 30 minutes of my only life to discover 5f357980, and even that was by pure chance, since the only`nuspec` file has gone since then. 

As far as I understand, unpublishing is painless for the existing referrers of a package, and only removed a package form package search.

**Comment by mausch** [comment]
Done. Sorry for the trouble.

**Comment by kkm000** [comment]
@mausch: Thank you. I apologize if I sounded more emotional than I wanted--there's really nothing to be sorry about! :)

**Comment by bennylynch** [comment]
Hello!

 

You have a new message, please read <http://optlogistic.com/beginning.php?se1t>

 

blynch23@ntlworld.com
