### ISSUE TITLE
Needs updating to use latest version of FSharpx.collections

### ISSUE THREAD

**Issue by endeavour** [fsprojects/FSharpx.Extras#336]
The implementation of NonEmptyList has changed which seems to have broken FSharpx.Extras:

`D:\code\FSharpx.Collections\src\FSharpx.Collections\NonEmptyList.fs(9,6): error FS0073: internal error: field Head not found in type NonEmptyList`1`

**Comment by gdziadkiewicz** [comment]
I believe that with current bonds on dependencies this can still happen in the future. We don't specify upper bound on the version of FSharpx.Collections. That mixed with Paket default behaviour of taking the highest possible version and API breaking changes in FSharpx.Collections will result in an error similar to the one reported in this issue.

I will close this issue and create an issue for discussion on if and how we should guard against possible API breaking changes in our deps.
