### ISSUE TITLE
New place for StructuredFormat

### ISSUE THREAD

**Issue by gsvgit** [fsprojects/FSharpx.Extras#338]
### Description

Seems that FSharpx is a strange place for StructuredFormat.  What about we move StructuredFormat to YC.PrettyPrinter? [More information and discussion available here](https://github.com/fsprojects/YC.PrettyPrinter/issues/17).

**Comment by dsyme** [comment]
@gsvgit Can you just take a copy of it?  And redesign the API surface area if you wish to?

**Comment by gsvgit** [comment]
@dsyme Well. Done.  Result is [available on NuGet](https://www.nuget.org/packages/YC.PrettyPrinter/).
