### ISSUE TITLE
What needs to be done to have a release compatible with .NET Standard 2.0?

### ISSUE THREAD

**Issue by oscarvarto** [fsprojects/FSharpx.Extras#359]
### Description

Current library cannot be used in projects targetting .NET Standard 2.0. I'm specially interested on Xamarin.Android. I don't know how difficult a change like this is, but with guidance, I could try to make a pull request.

**Comment by alex-bogomaz** [comment]
hello, you probably need to also convert dependencies such as "FSharpx.Async" and "FSharpx.Collections" to  .NET Standard 2.0. 
There is a PR of @enricosada for "FSharpx.Collections", however I'm not sure if it is "real" or for educational purposes :-)

**Comment by ChrSteinert** [comment]
I am currently in the process of migrating to SDK style project files, as a first step.
I also want to follow up with .NET Standard then.

**Comment by panesofglass** [comment]
Fixed in #360

**Comment by toburger** [comment]
When can we expect a nuget release?

**Comment by panesofglass** [comment]
@forki can you release?

**Comment by panesofglass** [comment]
@forki or could you grant me push permissions to nuget?
