### ISSUE TITLE
AssemblyVersion missing

### ISSUE THREAD

**Issue by drivehappy** [fsprojects/FSharpx.Extras#363]
### Description

The assembly information doesn't seem to be properly set.

### Repro steps

1. Open the properties dialog for FSharpx.Extras.dll in Windows Explorer, click on the Details tab and observe missing information for the following:
a. File description
b. File version
c. Product name
d. Product version
e. Language

2. Open FSharpx.Extras.dll in ILSpy, and observe that the AssemblyVersion is listed as 0.0.0.0

### Expected behavior

At the very least, the AssemblyVersion should match the Nuget release version.

### Actual behavior

AssemblyVersion is listed as 0.0.0.0

### Known workarounds

No known workarounds.

### Related information 

* Windows 10
* Investigated issue at FSharpx.Extras version 2.2.1

* Note: When I do the above steps for FSharpx.Async I see the expected information

**Comment by panesofglass** [comment]
It seems this _should_ be fixed with #360, but I don't see _any_ version listed in Windows Explorer properties. @drivehappy, can you look again with ILSpy?

**Comment by panesofglass** [comment]
Actually, I think we need to release a new version. Doesn't seem this has been released in a long time.

**Comment by gdziadkiewicz** [comment]
Fixed in 2.3.*
![image](https://user-images.githubusercontent.com/8547855/81513230-1c897700-9327-11ea-8ec7-9e4119ee9e79.png)
