### ISSUE TITLE
Mark TaskBuilder as Obsolete and point to TaskBuilder.fs

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FSharpx.Extras#368]
The task builder in FSharpx.Extras is obsolete and should be marked as Obsolete with a comment that points users in the right direction.

Previous text:
> 
>
> ### Description
>
> How are you supposed to use TaskBuilder with `Task`, i.e. not `Task<unit>` ?
>
> ### Repro steps
>
> ### Expected behavior
> 
> ```f#
>         member this.Batch cs= task {
>             use fs = File.Open(fileName, FileMode.Append, FileAccess.Write, FileShare.Read)
>             use w = new StreamWriter(fs)
>             w.WriteLine(serialize(cs |> List.toArray))
>             do! fs.FlushAsync()
>         }
> ```
> 
> ### Actual behavior
> 
> I'd expect it task computation builder to work with `Task` but it seems I need to do:
> ```f#
>         member this.Batch cs= task {
>             use fs = File.Open(fileName, FileMode.Append, FileAccess.Write, FileShare.Read)
>             use w = new StreamWriter(fs)
>             w.WriteLine(serialize(cs |> List.toArray))
>             do! fs.FlushAsync().ContinueWith<unit>( fun _ -> () )
>         }
> ```

**Comment by panesofglass** [comment]
I think we may want to remove this builder in favor of using https://github.com/rspeele/TaskBuilder.fs

**Comment by wallymathieu** [comment]
Good to know! So perhaps close this issue and create a pull request?

**Comment by panesofglass** [comment]
@wallymathieu, yes, that would be helpful! Thank you!

**Comment by panesofglass** [comment]
The PR should probably just mark the `TaskBuilder` here as `Obsolete` and indicate that users should use the other package.

**Comment by wallymathieu** [comment]
I've changed the description and title of this issue.

**Comment by wallymathieu** [comment]
This is related to #353
