### ISSUE TITLE
result computation expression not in the latest release?

### ISSUE THREAD

**Issue by njlr** [fsprojects/FSharpx.Extras#369]
### Description

Is the `result` computation expression not in the latest release?  

https://github.com/fsprojects/FSharpx.Extras/blob/c44c34e8cae0809e49bb0d6ca35fb5388b85190f/src/FSharpx.Extras/ComputationExpressions/Result.fs 

### Repro steps

Please provide the steps required to reproduce the problem

1. `dotnet add package FSharpx.Extras --version 2.2.1`

2. Write code like: 

```
open FSharpx
open FSharpx.Result

let myResultThing = result {
}
```

### Expected behavior

Can use `result`

### Actual behavior

`result` is not available. 

>  error FS0039: The value or constructor 'result' is not defined.

**Comment by panesofglass** [comment]
I don't think a new release has been published in quite some time. Please ping @forki or @sergey-tihon to see if someone with access can publish.

**Comment by njlr** [comment]
Would it be possible to make a new release? @forki @sergey-tihon

**Comment by mbuhot** [comment]
@panesofglass It looks like there is a newer release in the `RELEASE_NOTES.md` but not on Nuget.org yet? Am I missing something?

**Comment by panesofglass** [comment]
@mbuhot that's correct. I don't have access, last I checked, to release to NuGet.

**Comment by njlr** [comment]
*Bump* Who has access?

**Comment by njlr** [comment]
Related: https://github.com/fsprojects/FSharpx.Extras/issues/370

**Comment by panesofglass** [comment]
Published at long last!
