### ISSUE TITLE
Please publish a new version to NuGet.org

### ISSUE THREAD

**Issue by mbuhot** [fsprojects/FSharpx.Extras#370]
### Description

Hello and thanks for creating FSharp.Extras.

Please publish a new version to NuGet.org.
I found it confusing to see a [version 2.3.0](https://github.com/fsprojects/FSharpx.Extras/blob/master/RELEASE_NOTES.md#230---12092018) listed in the release notes, but no corresponding version on NuGet.org.

### Repro steps

n/a

### Expected behavior

n/a

### Actual behavior

n/a

### Known workarounds

Paket GitHub reference?

### Related information 

n/a

**Comment by nightroman** [comment]
Is this on the radars?

> I found it confusing to see a [version 2.3.0](https://github.com/fsprojects/FSharpx.Extras/blob/master/RELEASE_NOTES.md#230---12092018) listed in the release notes, but no corresponding version on NuGet.org

It should not be in the release notes. Or the wording should be different. Or maybe the maintainers just forgot to push the package? Pinging.

**Comment by mbuhot** [comment]
@nightroman I am guessing it could have something to do with the dependencies not all having released a .net standard version yet?

`FSharpx.Async` has open issue and PR to update to .net standard: 
https://github.com/fsprojects/FSharpx.Async/pull/43

`FSharpx.Collections` version supporting .net standard is still in beta: 
https://github.com/fsprojects/FSharpx.Collections/blob/master/RELEASE_NOTES.md#200-beta4---unreleased

cc: @forki / @mausch / @panesofglass

**Comment by ForNeVeR** [comment]
I believe that all the dependencies support .NET Standard now. 

What could we do to help with publishing the .NET Standard version of FSharpx.Extras now?

**Comment by panesofglass** [comment]
@fsprojects, may I have push access for this project, as well?

**Comment by sergey-tihon** [comment]
@panesofglass sorry, for delay, I've added you as on owner for NuGet package. Request wait for your approval.

**Comment by panesofglass** [comment]
@sergey-tihon, I've just published FSharpx.Extras 2.3.0, but I still don't have access to [FSharpx.Text.StructuredFormat](https://www.nuget.org/packages/FSharpx.Text.StructuredFormat/). Would you mind granting me access to that one, as well?

**Comment by sergey-tihon** [comment]
@panesofglass Done

**Comment by nightroman** [comment]
On adding the lastest package

**Comment by nightroman** [comment]
On adding the latest package (2.3.0) to a netcoreapp2.1 project, Visual Studio 2019 shows the following warnings

```
Warning NU1701  Package 'FSharpx.Async 1.13.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
Warning NU1602  FSharpx.Async 1.13.2 does not provide an inclusive lower bound for dependency FSharp.Control.AsyncSeq. An approximate best match of FSharp.Control.AsyncSeq 1.0.0 was resolved.
Warning NU1701  Package 'FSharpx.Collections 1.17.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
```

Is this normal/expected?

**Comment by nightroman** [comment]
I am not an expert but the package dependencies look out of date

```
<dependency id="FSharpx.Async" version="1.13.2" exclude="Build,Analyzers" />
(Latest = 1.14.0)
<dependency id="FSharpx.Collections" version="1.17.0" exclude="Build,Analyzers" />
(Latest = 2.0.0)
```

**Comment by panesofglass** [comment]
PR welcome

**Comment by eriawan** [comment]
@panesofglass 
> PR welcome

I have submitted a PR to update dependencies to FSharpx.Async and FSharpx.Collections in #373 

Please review and thanks in advance :)
