### ISSUE TITLE
Restore documentation generation

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FSharpx.Extras#378]
I'm removing documentation generation in #374 as part of an update to FAKE 5. I don't know how to generate docs in FAKE 5 on .NET Core, so help is appreciated.

**Comment by matthid** [comment]
Usually, the way to do it is to use the cli tool (fsformatting.exe) until fsharp.formatting has a netstandard based version

**Comment by panesofglass** [comment]
Thanks, @matthid. Would you mind linking to an example?

**Comment by matthid** [comment]
See https://github.com/fsharp/FAKE/blob/4da532f432ec78aeddb427fea6c25973c8bf797d/build.fsx#L437
