### ISSUE TITLE
Newest version of package has not been published to NuGet.

### ISSUE THREAD

**Issue by gdziadkiewicz** [fsprojects/FSharpx.Extras#384]
### Description

I need to access new feature (net452 support) that has been merged to master but didn't get deployed to NuGet yet. If any issues prevent the maintainers from deploying the new version to NuGet I'm willing to solve them or help to solve them.

### Solution
One of the ppl with right permissions deploys new version to NuGet.

**Comment by panesofglass** [comment]
@gdziadkiewicz were you able to get this published?

**Comment by gdziadkiewicz** [comment]
Yes, but only FSharpx.Extras. Could you also add me as an owner to https://www.nuget.org/packages/FSharpx.Text.StructuredFormat ?

**Comment by gdziadkiewicz** [comment]
@panesofglass ping

**Comment by panesofglass** [comment]
Hmm ... I think @fsprojectsgit has to do that, but I’ll try.

**Comment by panesofglass** [comment]
Never mind! I was able to add you!

**Comment by gdziadkiewicz** [comment]
@panesofglass Great! Now I have all the tools necessary :) Thank you :)
