### ISSUE TITLE
Results module lacks functionality

### ISSUE THREAD

**Issue by gdziadkiewicz** [fsprojects/FSharpx.Extras#389]
### Description

`Result` module lacks the functionality provided by `Option` module. Missing stuff:
* `Result.getOrElse`
* `Result.getOrElseF`
* `Result.getOrFail`
* `Result.getOrRaise`
* `Result.either : ('a->'c )-> ('b->'c) -> Result<'a,'b'> -> 'c`

I took the names from `Option` module, but wouldn't mind coming with something better.

### Repro steps
N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Known workarounds
N/A

### Related information 
N/A

**Comment by panesofglass** [comment]
Should this be added, or should we just direct people to Chessie and obsolete this functionality?

**Comment by gdziadkiewicz** [comment]
IMO it should be added. Chessie is built around its own type (https://github.com/fsprojects/Chessie/blob/master/src/Chessie/ErrorHandling.fs#L7-L11) that's different from the one exported by `FSharp.Core`. `Result` module in FSharp.Extras provides functions and builder to work with `Result` provided by FSharp.Core.
