### ISSUE TITLE
Website does not mention functional wrappers

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/FSharpx.Extras#399]
### Description

The website lists many of the features of FSharpX, but it does not mention the functional wrappers around instance methods, eg for Strings (https://fsprojects.github.io/FSharpx.Extras/reference/fsharpx-string.html).

I was not aware that it had these, and thought FSharpX was for "hardcore functional" stuff, HTTP stuff, and C# interop.

### Repro steps

Visit[ page](https://fsprojects.github.io/FSharpx.Extras/index.html), read intro.

### Expected behavior

You learn that functional wrappers exist.

### Actual behavior

You do not learn that functional wrappers exist.

### Known workarounds

n/a

### Related information 

n/a

**Comment by gdziadkiewicz** [comment]
Hi @pbiggar , thanks for creating the issue!

I agree that we need to create good examples to be used in the docs that would show the idea behind/gain from those functional wrappers (maybe side by side comparison of code that uses `string` instance methods and functional wrappers?). Are you willing to help? Anything from loose ideas through a draft to full implementation or review would be good.

I'm nearly finished with #378 which is a blocker for releasing docs changes.

**Comment by gdziadkiewicz** [comment]
#378 has been resolved - I'm going to take a look at this.
