### ISSUE TITLE
Some files mention licenses different than Unlicense.

### ISSUE THREAD

**Issue by gdziadkiewicz** [fsprojects/FSharpx.Extras#405]
### Description

The whole package is licensed under Unlicese, but some of the files mention different licenses.

Files:
* https://github.com/fsprojects/FSharpx.Extras/blob/ac5053bd5cdaf8ec82099efe4d25a100be0e5fb8/docs/Santa.fsx#L1-L12
* https://github.com/fsprojects/FSharpx.Extras/blob/d51ce763762b1e277f679d01b76504da00a67b6b/src/FSharpx.Extras/Stm.fs#L1-L12
* https://github.com/fsprojects/FSharpx.Extras/blob/d51ce763762b1e277f679d01b76504da00a67b6b/src/FSharpx.Extras/Pluralizer.fs#L1-L11
* https://github.com/fsprojects/FSharpx.Extras/blob/ac5053bd5cdaf8ec82099efe4d25a100be0e5fb8/docs/StructuredFormatSample.fsx#L1-L4
* https://github.com/fsprojects/FSharpx.Extras/blob/d51ce763762b1e277f679d01b76504da00a67b6b/src/FSharpx.Extras/Net.fs#L1-L4
* https://github.com/fsprojects/FSharpx.Extras/blob/ac5053bd5cdaf8ec82099efe4d25a100be0e5fb8/docs/WebProxy.fsx#L1-L4

@tpetricek @dsyme Do you know if it was intentional or they were omitted by mistake? Do you know what needs to be done in order to fix that?

cc @forki for help as he may know/remember more - license change was made in his commit  https://github.com/fsprojects/FSharpx.Extras/commit/80133ee939a0f1e90006e98bc318ac5cdeaf022c#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1d

**Comment by dsyme** [comment]
I guess they were copied across.  

Just switch them all to Unlicense.

**Comment by dsyme** [comment]
Well, I guess we should just list the different licenses until people approve

I give permission to switch the Microsoft Pluralizer sample code to Unlicense

cc @gneverov for the others

**Comment by tpetricek** [comment]
I give permission to switch the two "F# async extensions" files to Unlicense.

**Comment by gdziadkiewicz** [comment]
I managed to contact @gneverov via email:

> Re: License change in FSharpX.Extras
> Gregory Neverov <gregory.neverov@gmail.com>
> Mon 2021-01-04 21:53
> To: Grzegorz Dziadkiewicz <grzegorz@dziadkiewicz.com>
> Hi Grzegorz,
> 
> I'm surprised this code still exists! You can change the license to anything you need to.
> 
> 
>
