### ISSUE TITLE
Restore some Task functions

### ISSUE THREAD

**Issue by Micha-kun** [fsprojects/FSharpx.Extras#408]
Since the last version (3.0.0), a lot of Task functions (Task.Catch, Task.ParallelWithThrottle) were removed and now my code fails to compile. I understand the removal of Computation Expression, but those methods were usable. Or were removed because they already exist in another library? Thank you so much.

**Comment by gdziadkiewicz** [comment]
Hi, I removed them, because they were implemented using that Task CE and I wasn't able to reimplement them cheaply. I will take another look. Is sticking with the previous version until I'm done a feasible workaround for you?

**Comment by Micha-kun** [comment]
It's what I'm doing for now, using previous version.

**Comment by Micha-kun** [comment]
Any news about updating NuGet package with this restore? Thank you!

**Comment by gdziadkiewicz** [comment]
I will release it as soon as I get the CI build working again. ETA today

**Comment by gdziadkiewicz** [comment]
Released 3.1.0 - https://www.nuget.org/packages/FSharpx.Extras/3.1.0

**Comment by gdziadkiewicz** [comment]
@Micha-kun were you able to check it out?

**Comment by Micha-kun** [comment]
Yep! It seems all ok now :D Thank you!
