### ISSUE TITLE
Please include samples that use or explain the State monad

### ISSUE THREAD

**Issue by sonicbhoc** [fsprojects/FSharpx.Extras#413]
### Description

I feel like the State monad could be perfect for the code I'm writing, but I can't get it to to work for me. I don't understand it, and most of what I find out there is for Haskell.

### Repro steps

1. Look for examples.
2. Find no examples.

### Expected behavior

1. Look for examples.
2. Find examples.

**Comment by gdziadkiewicz** [comment]
Hi, I'm willing to provide samples. Can you share your use case?

In the meantime, I will provide a generic sample that shows how to read, write and execute the monad.

**Comment by sonicbhoc** [comment]
Sure. I am doing an event-sourced aggregate. I'm new to the language and the Functional Programming paradigm in general and I'm sure I can abstract away a lot more than I am now (I need to learn more about monoids and the like; hence my question).

I have 2 workflows that pass around state: one is validation and the other is actually updating the state by modifying an element of the list holding the types. I'm not even sure the state monad is the right way to do what I'm doing, honestly.

**Comment by gdziadkiewicz** [comment]
Can you check the draft of the generic sample in https://github.com/gdziadkiewicz/FSharpx.Extras/tree/Fix_%23413_add_state_sample ?

**Comment by gdziadkiewicz** [comment]
While working on it I noticed that the State monad functions are not fully documented - would be nice to fix that.
