### ISSUE TITLE
Online documentation is out of date

### ISSUE THREAD

**Issue by kfl** [fsprojects/FSharpx.Extras#430]
### Description

The API reference at <http://fsprojects.github.io/FSharpx.Extras/reference/index.html> seems to be out of date,

For instance, the last version in the Release Notes at <http://fsprojects.github.io/FSharpx.Extras/release-notes.html> is `2.2.1 - 29.01.2017`.

Similarly, the `Prelude` module is listed to be part of the `FSharpx.Functional` namespace at <http://fsprojects.github.io/FSharpx.Extras/reference/fsharpx-functional-prelude.html>. Where is should have been listed as part of the `FSharpx` namespace as it has been since the 2.3.1 release.

**Comment by bartelink** [comment]
Looks like the release notes have been replaced with GitHub releases
https://github.com/fsprojects/FSharpx.Extras/releases
Normally nuget.org is the best way to get a high level on the versions being used IRL https://www.nuget.org/packages/fsharpx.extras#versions-body-tab

**Comment by kfl** [comment]
Sorry, I didn't make myself clear. It is not a big problem that the release notes are old (I know where to find them on github). I merely gave a  link to the release notes to point out when the online documentation was last updated. You can get the same information if you look at the `gh-pages` branch, where you can seem that the online documentation was last updated seven years ago.

However, I think it is sad that online documentation isn't updated, so that it's currently pointing to old (misleading) examples and outdated API documentation. Especially since the `docs` directory seems to be maintained (and has cleaned up the examples) and that the API documentation is also updated.

**Comment by bartelink** [comment]
👍 I'm just a lurker (and have never added a ref to it personally!)
Ultimately the answer is obviously to automate the push (repos here have access to GHA)...

**Comment by gdziadkiewicz** [comment]
Hi, if I remember correctly, I made an attempt at fixing the docs and releasing it but failed and had to rollback (I don't recall the blocking issue). If you are that somebody, then I can cheer, review the PR and hope for you to be luckier than I was at the previous attempt.

**Comment by kfl** [comment]
If you are interested then I recently set up generation of online documentation via `fsdocs` with GHA: <https://github.com/diku-dk/diku-canvas/blob/main/.github/workflows/package_and_docs.yml>

Although I'm using the new github-pages deployment method where you are using the `gh-pages` branch method.

**Comment by gdziadkiewicz** [comment]
Hi,

I just fixed the issue that bugged me in the past and published new docs :)
