### ISSUE TITLE
FSharpx.Extras v3.2.0 breaks compilation

### ISSUE THREAD

**Issue by Micha-kun** [fsprojects/FSharpx.Extras#436]
### Description

FSharpx.Extras v3.2.0 has a forced restriction that Fsharp.Core requires to be (>= 6.0.6 && < 6.1.0), making projects using other versions to break. v3.1.0 didn't have that restriction (>= 4.6.2).

### Repro steps

Create an F# project with .Net 8 and try to add FSharpx.Extras v3.2.0 nuget

### Expected behavior

Project with FSharpx.Extras compiles correctly

### Actual behavior

Project with FSharpx.Extras fails to compile

### Known workarounds

Install FSharpx.Extras v3.1.0 or force Fsharp.Core to be (>= 6.0.6 && < 6.1.0)

### Related information 

* Operating system: **Windows 11**
* .NET Runtime, CoreCLR or Mono Version: **.Net 8.0**

**Comment by gdziadkiewicz** [comment]
Hi @Micha-kun I will fix that tomorrow

**Comment by gdziadkiewicz** [comment]
Hi, I just published a new version (3.2.1) with the requirement on FSharp.Core relaxed. Can you confirm if it works for you as expected?

**Comment by bert2** [comment]
Thanks for the fix! I don't see anymore compiler errors here :)

**Comment by Micha-kun** [comment]
> Hi, I just published a new version (3.2.1) with the requirement on FSharp.Core relaxed. Can you confirm if it works for you as expected?

Yep! It's working now :) Thank you!

**Comment by OkkeHendriks** [comment]
Yes, checked again with 3.2.0 -> compile warning; at 3.2.1 it is fixed! Thanks.
